// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKMcthU7fLfs2ZKdHWnlVIo4t1FbCQarg',
    appId: '1:1018920622215:web:b3e7071bb3f57670404022',
    messagingSenderId: '1018920622215',
    projectId: 'monsters-app-2660c',
    authDomain: 'monsters-app-2660c.firebaseapp.com',
    storageBucket: 'monsters-app-2660c.firebasestorage.app',
    measurementId: 'G-Y8KRH47L79',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6uF951i1gLe2o8c2sfasCZ9ByUKsHaGs',
    appId: '1:1018920622215:android:05d27435de9b04b1404022',
    messagingSenderId: '1018920622215',
    projectId: 'monsters-app-2660c',
    storageBucket: 'monsters-app-2660c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSYjczP76NfNW7nLwuRTGoaI-zduIlKvQ',
    appId: '1:1018920622215:ios:0880e5676dcac87e404022',
    messagingSenderId: '1018920622215',
    projectId: 'monsters-app-2660c',
    storageBucket: 'monsters-app-2660c.firebasestorage.app',
    iosBundleId: 'com.example.prueba1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDSYjczP76NfNW7nLwuRTGoaI-zduIlKvQ',
    appId: '1:1018920622215:ios:0880e5676dcac87e404022',
    messagingSenderId: '1018920622215',
    projectId: 'monsters-app-2660c',
    storageBucket: 'monsters-app-2660c.firebasestorage.app',
    iosBundleId: 'com.example.prueba1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAKMcthU7fLfs2ZKdHWnlVIo4t1FbCQarg',
    appId: '1:1018920622215:web:c59ed630b4bac7a3404022',
    messagingSenderId: '1018920622215',
    projectId: 'monsters-app-2660c',
    authDomain: 'monsters-app-2660c.firebaseapp.com',
    storageBucket: 'monsters-app-2660c.firebasestorage.app',
    measurementId: 'G-L3GZCPPHV9',
  );
}
